### ISSUE TITLE
DtdAnalyzer-0.5/dtd2xml2json: Need to tell me what to do with element

### ISSUE THREAD

**Issue by pdc-kaminaga** [ncbi/DtdAnalyzer#56]
I tried DtdAnalyzer-0.5/dtd2xml2json.
(a) pattern succeeded. But (b) pattern output "Need to tell me what to do with element" message.
Please tell me how to solve the problem.

(input .dtd file)
　<！ELEMENT conference  (text | (conftitle,confplace)) >
   ・
   ・
　<！ELEMENT conftitle  (#PCDATA) > --- (a)
   ・
   ・
　<！ELEMENT confplace  (#PCDATA | address)* >  --- (b)

(output .xsl file)
   <xsl:template match="・・・| conference |・・・">
      <xsl:param name="context" select="&#34;unknown&#34;"/>
      <xsl:call-template name="a">
         <xsl:with-param name="context" select="$context"/>
      </xsl:call-template>
   </xsl:template>
   ・
   ・
    <xsl:template match="・・・| conftitle |・・・>
      <xsl:param name="context" select="&#34;unknown&#34;"/>
      <xsl:call-template name="s">
         <xsl:with-param name="context" select="$context"/>
      </xsl:call-template>
   </xsl:template>

(console)
Need to tell me what to do with element confplace

**Comment by Klortho** [comment]
This tool doesn't provide a complete out-of-the-box solution. It automatically generates XSLT templates for elements that have a very simple content model, but for anything complex, you have to decide what the JSON will look like, and write your own template.

So, because `confplace` has mixed content, it falls into this category.

**Comment by pdc-kaminaga** [comment]
I will try to create a template.
Thank you.
